name: Build and Deploy to GCP Kubernetes

on:
  workflow_dispatch

jobs:
  DockerImageBuild:
    runs-on: ubuntu-latest      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure Google Cloud credentials
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: "fifth-repeater-448910-s5"
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}

    - name: Authenticate gcloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
                 
    - name: Set environment variables
      run: |
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
        echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build --build-arg DB_HOST=${{ secrets.DB_HOST }} \
                     --build-arg DB_NAME=${{ secrets.DB_NAME }} \
                     --build-arg DB_USER=${{ secrets.DB_USER }} \
                     --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
                     -t reverse-ip-app .

    - name: Push Docker image to Google Container Registry
      run: |
        gcloud artifacts docker images list us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/reverse-ip-app
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev
        docker tag reverse-ip-app us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/reverse-ip-app/reverse-ip
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/reverse-ip-app/reverse-ip

  HelmDeploy:
    runs-on: ubuntu-latest
    needs: DockerImageBuild
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure Google Cloud credentials
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: "fifth-repeater-448910-s5"
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}

    - name: Authenticate gcloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Add Helm repository
      run: |
        helm repo add stable https://charts.helm.sh/stable
        helm repo update

    - name: Verify cluster access
      run: |
        gcloud container clusters describe reverse-ip-cluster --region us-central1

    - name: Deploy with Helm
      run: |
        gcloud components install gke-gcloud-auth-plugin
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud container clusters get-credentials reverse-ip-cluster --region us-central1 --project ${{ secrets.GCP_PROJECT_ID }}

        helm upgrade --install reverse-ip-release ./helm/reverse-ip-chart \
          --set image.repository=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/reverse-ip-app/reverse-ip \
          --set image.tag=latest \
          --set service.nodePort=30001 \
          --set env.DB_HOST=${{ secrets.DB_HOST }} \
          --set env.DB_NAME=${{ secrets.DB_NAME }} \
          --set env.DB_USER=${{ secrets.DB_USER }} \
          --set env.DB_PASSWORD=${{ secrets.DB_PASSWORD }}
