name: Build and Deploy to GCP Kubernetes

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Build Docker image
      run: |
        docker build -t reverse-ip-app .

    - name: Push Docker image to Google Container Registry
      run: |
        gcloud auth configure-docker
        docker tag us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/reverse-ip-app/reverse-ip
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/reverse-ip-app/reverse-ip
